version: '3'

services:
  workspace:
    build: workspace
    container_name: workspace
    working_dir: /workspace
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
      - /workspace/node_modules
